/**
 * answer.ts — Zod schemas + TypeScript types for all API contracts
 *
 * WHY ZOD?
 * Zod lets us define the "shape" of data and validate it at runtime.
 * If the data doesn't match the shape, Zod gives a clear error instead of
 * crashing with a confusing undefined error deep in the code.
 *
 * FLOW:
 *   HTTP Request JSON  →  safeParse(schema)  →  typed object  →  business logic
 *   LLM JSON output    →  safeParse(schema)  →  typed object  →  send to client
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// INBOUND — what the client sends TO us
// ---------------------------------------------------------------------------

/**
 * Schema for POST /chat request body
 *
 * Example valid input:
 *   { "message": "What is RAG?", "sessionId": "abc-123" }
 *
 * Example invalid input (will be rejected):
 *   { "message": "" }  ← fails min(1) check
 *   { }                ← missing required "message" field
 */
export const ChatRequestSchema = z.object({
  message: z.string().min(1),       // user's question, must not be empty
  sessionId: z.string().optional(), // optional — if omitted, server generates one
});

/**
 * Schema for POST /ingest request body
 *
 * Example valid input:
 *   {
 *     "content": "RAG stands for Retrieval Augmented Generation...",
 *     "filename": "rag-intro.txt",
 *     "metadata": { "author": "admin", "topic": "RAG" }
 *   }
 */
export const IngestRequestSchema = z.object({
  content: z.string().min(1),                        // full document text
  filename: z.string().min(1),                       // used as document identifier in Chroma
  metadata: z.record(z.string()).optional(),         // any extra key-value pairs you want stored
});

// ---------------------------------------------------------------------------
// OUTBOUND — what we send BACK to the client
// ---------------------------------------------------------------------------

/**
 * A single citation — one retrieved chunk that was used to build the answer
 *
 * Example:
 *   {
 *     "source": "rag-intro.txt",
 *     "chunk": "RAG stands for Retrieval Augmented Generation...",
 *     "score": 0.92
 *   }
 *
 * score: similarity score between 0 and 1 (1 = perfect match)
 */
export const CitationSchema = z.object({
  source: z.string(),           // filename the chunk came from
  chunk: z.string(),            // the actual text of the retrieved chunk
  score: z.number().optional(), // relevance score (higher = more relevant)
});

/**
 * Full response for POST /chat
 *
 * Example:
 *   {
 *     "answer": "RAG combines vector search with LLMs...",
 *     "citations": [{ "source": "rag-intro.txt", "chunk": "...", "score": 0.92 }],
 *     "followUpQuestions": ["How does chunking work?", "What is a vector DB?"],
 *     "sessionId": "abc-123"
 *   }
 *
 * followUpQuestions: generated by LLM in Phase 2 (currently empty array)
 */
export const ChatResponseSchema = z.object({
  answer: z.string(),
  citations: z.array(CitationSchema),
  followUpQuestions: z.array(z.string()),
  sessionId: z.string(),
});

/**
 * Response for POST /ingest
 *
 * Example:
 *   { "success": true, "chunksStored": 3, "filename": "rag-intro.txt" }
 */
export const IngestResponseSchema = z.object({
  success: z.boolean(),
  chunksStored: z.number(), // how many chunks were created and stored in Chroma
  filename: z.string(),
});

// ---------------------------------------------------------------------------
// TypeScript types — inferred directly from Zod schemas (no duplication)
// ---------------------------------------------------------------------------

// Instead of writing: interface ChatRequest { message: string; sessionId?: string }
// Zod infers it automatically from the schema above
export type ChatRequest = z.infer<typeof ChatRequestSchema>;
export type ChatResponse = z.infer<typeof ChatResponseSchema>;
export type IngestRequest = z.infer<typeof IngestRequestSchema>;
export type IngestResponse = z.infer<typeof IngestResponseSchema>;
export type Citation = z.infer<typeof CitationSchema>;
